### ISSUE TITLE
add usage instructions

### ISSUE THREAD

**Issue by matthiasbalke** [lukejpreston/junit_viewer#11]
It would be good to see which switches and parameters are available.

This could be realized unix style: if no parameter is given or the only parameter is -h|--help.

**Comment by lukejpreston** [comment]
you mean like junit-viewer --help???

**Comment by lukejpreston** [comment]
I can add something

**Comment by lukejpreston** [comment]
this will be covered in version 4, but if you call junit_viewer version 3 with no arguments I think it gives you this

**Comment by lukejpreston** [comment]
if you now do junit_viewer --help you get the help and if you just type junit_viewer you also get the help
