### ISSUE TITLE
add error message if no tests are found

### ISSUE THREAD

**Issue by matthiasbalke** [lukejpreston/junit_viewer#12]
In case no tests are found, the page freezes and displays "loading data...".

Simply send an empty JSON and handle that displaying a "no test results" message.

**Comment by lukejpreston** [comment]
This is being covered in version 4 of junit viewer

**Comment by lukejpreston** [comment]
have a sneakpeak at [version 4 branch](https://github.com/lukejpreston/junit_viewer/tree/new_look_with_skeleton)
and open the file "no_file.html" in your browser and let me know what you think

**Comment by lukejpreston** [comment]
I am going to close this but it is there
