### ISSUE TITLE
Nested tests suites are not displayed

### ISSUE THREAD

**Issue by JasperMaes** [lukejpreston/junit_viewer#15]
Hello,

When generating a JUnit file it is possible to nest testsuites but they are not recognized by the viewer.

Would it be possible to add this functionallity?

**Example:**
If I remove the testsuite with name *Enclosing test suite*, the parsing works otherwise I get an error.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
   <testsuite name="Enclosing test suite" failures="4" skipped="0" tests="4" time="10.54">
      <testsuite name="Suite 1" failures="0" skipped="0" tests="0" time="0" />
      <testsuite name="Suite 2" failures="4" skipped="0" tests="4" time="0">
         <testcase name="Testcase 1" time="0" status="0" />
         <testcase name="Testcase 2" time="0" status="0" />
         <testcase name="Testcase 3" time="0" status="0" />
         <testcase name="Testcase 4" time="0" status="0" />
      </testsuite>
   </testsuite>
</testsuites>
```

Thanks!

Jasper

**Comment by lukejpreston** [comment]
Is that example data something I use for testing? I would like to extend my current test data as long as that data is correct :smile_cat:

**Comment by japus** [comment]
Yep, that data is correct. The only thing that isn't correct is the time. The total time of the enclosing test suite doesn't correspond to the sum of the individual tests / test suites. Do you need me to correct that?

**Comment by lukejpreston** [comment]
I am trying to think of a good way to display this information without cluttering the view with crazy nested test suites, but I want this to be apart of version 4 which I am working on now. Once version 4 is released (should be soon) then I would like to bounce some ideas around with @JasperMaes  @szikszail 

it is a branch called new_look_with_skeleton if you wish to have a look check it out and then open valid_data.html to see something which is getting there

**Comment by lukejpreston** [comment]
the main thing I can think of is concatonating the suite names together

e.g. in this case

Enclosing test suite Suite 1
   test 1
   ...
Enclosing test suite Suite 2
   test 1
   ...

**Comment by lukejpreston** [comment]
I have done that now on on [version 4 branch](https://github.com/lukejpreston/junit_viewer/tree/new_look_with_skeleton)

If you have any better ideas let me know

it is using the test data in __tests__/data/complete_multi_suites.xml and currently nested suites is at the bottom

**Comment by JasperMaes** [comment]
I checked the valid_data file from the branch and it looks nice. I don't see another possibility than showing the different test suites under each other. 

The only thing I don't really like is the amount of space the individual lines take up. There is a lot of room above and below the messages. I'd reduce the padding a bit to like 2 or 3 pixels for the top and bottom. That way you can show more on a page which is after all what we're looking for, lots of data presented in as little space as possible. The same goes for the red, green and blue buttons indicating the test status.

Some other ideas I'll just put here, you can do with them whatever you want. 
- I like @szikszail's idea of adding a tree. It would be easier to navigate multiple test suites when you have an overview on the left for example. Now you have to start collapsing the other test suites etc. 
- You could add the search boxes in the left column as well. They're extremely useful, you shouldn't hide them by default.
- You could also show the or a part first line of the message in the test button itself, next to the test title just to give an idea of what's caused the error. Often the first line says enough. That way you could also collapse the test by default showing even more test on a single page. Of course the amount of empty space depends on the size of the window.
- As a last point, I liked the previous colors better, they're easier on the eyes.

It's looking really good, I'm looking forward to the new version. Just tell me if you need some help implementing some of the features. I don't really have a lot of spare time but I'll see what I can do.

Jasper

**Comment by lukejpreston** [comment]
hey just want to point out this update (it's a different branch than previous one)
[version 4](https://github.com/lukejpreston/junit_viewer/tree/version_4)
I am pretty excited by it as everything in it is working

I like the idea behind the single line messages I think I will put that in

I think searching should be easier to access as well because it is really powerful (was instant on my 3400+ tests)

I have nested suites as well and it looked fine with the long named suites so I am not sure I want to implement the tree after seeing that but it would be cool to see what you think

I have changed the code so much I am just working on the entry point to the tool now. I am also adding unit tests which is something I regretted not doing because I couldn't simply refactor it (though I would have written again anyway :smile_cat:)

**Comment by lukejpreston** [comment]
I have tagged an released it into npm, have a play and see whether it is working well

**Comment by lukejpreston** [comment]
I am going to leave it currently to do the long names instead of any other fancy thing. I have done some of the changes which are suggested above and I will split this out into separate issues in order to track them properly (if I miss any please say)
