### ISSUE TITLE
Support and display nested testsuties.

### ISSUE THREAD

**Issue by szikszail** [lukejpreston/junit_viewer#17]
Hi,

I have a requests to display nested testsuites in a tree-like design. I plan to implement is soon in my forked repository. I just wonder that are you interested in it to be a part of junit_viewer?

First of all, it will handle the issue described here: https://github.com/lukejpreston/junit_viewer/issues/15
After, I plan to add a new command line switch, i.e. --tree what will display the testsuites in this tree-like design. Without this flag, the suites are displayed as now, in a flat design.

About https://github.com/lukejpreston/junit_viewer/issues/15, if you will provide a solution for that, I will wait until it is ready.

**Comment by lukejpreston** [comment]
I am in the middle of creating version 4, and I was thinking about this as part of version 4. Also version 4 doesn't use jquery and is loads quicker. I agree though it sounds good

**Comment by lukejpreston** [comment]
I am going to close this issue and move this discussion to #15
