### ISSUE TITLE
Parse error when escaped XML is used in failure body

### ISSUE THREAD

**Issue by botchniaque** [lukejpreston/junit_viewer#23]
I have junit report generated by [python behave](https://pythonhosted.org/behave/behave.html), but when I try to view it using junit-viewer , I get a parse error. Report contains escaped XML entities in the `<failure/>` tag's body.

error says:
`Parse Error: <FixtureRequest for <Function 'test_edit_ssh_key'>>`

XML I try to view:

```
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="15" name="pytest" skips="0" tests="41" time="437.073">
    <testcase classname="tests.dcd.test_ssh_key_manager" file="tests/dcd/test_ssh_key_manager.py" line="39"
              name="test_edit_ssh_key" time="15.799032211303711">
        <failure
                message="lib.dcd.dcd.NodeNotFoundError: Element not found for:[&apos;SshKeysTab&apos;, &apos;sshKeyListView&apos;, &apos;listView&apos;, &apos;=Test ssh key 2332098&apos;, &quot;$/parent::*[@role=&apos;option&apos;]&quot;] 
 xpath://*[@ui=&quot;SshKeysTab&quot;]//*[@ui=&quot;sshKeyListView&quot;]//*[@ui=&quot;listView&quot;]//*[text()=&apos;Test ssh key 2332098&apos;]/parent::*[@role=&apos;option&apos;]">
            request = &lt;FixtureRequest for &lt;Function &apos;test_edit_ssh_key&apos;&gt;&gt;
        </failure>
    </testcase>
</testsuite>
```

**Comment by lukejpreston** [comment]
I am not sure but I think this might be a feature in junit viewer...

If you return xml/html it will render it in the output code, this is really useful for things like screenshot testing where you want to report the images.

I have been on holiday for a while and a bit busy but will look into it now

**Comment by lukejpreston** [comment]
this project is now deprecated, please see https://github.com/lukejpreston/xunit-viewer which supports the same features

I think this works there
