### ISSUE TITLE
Feature request: allow it to run within a browser

### ISSUE THREAD

**Issue by gwynjudd** [lukejpreston/junit_viewer#26]
I want to allow a user to (say) paste in XML from a test run and render it in browser instead of in node. For my purposes, there are two parts to this:

1. allow it to be built in browserify by making some code tweaks so that the `readFileSync` calls in render.js can be resolved at build time by brfs
2. add a `renderXML` method that be called with text content of XML to be rendered instead of a file name

I have a PR almost ready to submit for this.

**Comment by lukejpreston** [comment]
so this makes it that junit_viewer can be called in the browser?

Can you create some sort of sample thing #27 in the README or a separate file as part of the gh-pages to show this in action?

**Comment by lukejpreston** [comment]
appologies I thought I had merged this, but apparently merge conflict, once you update your branch I will merge and do an update

**Comment by gwynjudd** [comment]
@lukejpreston I think the conflict should be fixed now
