### ISSUE TITLE
Make it work with output of nightwatch

### ISSUE THREAD

**Issue by wadeziegler** [lukejpreston/junit_viewer#29]
I'm wondering if you can make it work with Nightwatchjs.

Nightwatch produces something like this where the real failure message shows up in the message sttribute.  junit-viewer shows the value instead.

<testcase name="DOV Index Page" time="9.938" assertions="1">  <failure message="Timed out while waiting for element &lt;#index-link-dov&gt; to be present for 5000 milliseconds.">    at Object.module.exports.DOV Index Page (C:\devel\dov\tests\tests\dov.js:5:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

**Comment by lukejpreston** [comment]
junit viewer favours the inner message over the attributes. it has to pick one or the other. Is nightwatchjs producing 2 different values for this? If so the only thing I can think to do is make it so there is an extra option to pick whether you want to use attributes or to use inner message. But it might be simpler to raise it with nightwatch...

**Comment by lukejpreston** [comment]
this project is now deprecated, please see https://github.com/lukejpreston/xunit-viewer which supports the same features
