### ISSUE TITLE
Same test suite in multiple environments

### ISSUE THREAD

**Issue by jaiminpanchal27** [lukejpreston/junit_viewer#30]
I am using Nightwatch and browserstack to test my testcases in multiple environments. Now nightwatch generates junit xml report. So for e.g. 

Spec file: user_spec.js
Environments: Chrome51_Windows10, Firefox46_Windows8.1
Nightwatch generates junit reports with these filenames:
Chrome51_Windows10_user_spec.js,
Firefox46_Windows8.1_user_spec.js

When i use your plugin and create html it merges the test cases of both xml files and generates one single html file. When i view this file there is no way to differentiate between test cases.

The solution i am thinking is creating different html file for each environment and creating a single html file to access each one.

Any thoughts on above.. ? Maybe you can add new feature for multiple environments.

**Comment by lukejpreston** [comment]
if you create an xml for each test then run junit viewer for each xml you get what you are looking for...

**Comment by jaiminpanchal27** [comment]
Yes correct but what if i run my test case on two environments, so in that case i will have two exact same xml file with different name. 
Anyway i have solved my issue with solution described above. Just wanted to share with you so that if you have any idea to add some features for browserstack or saucelabs.
Thanks.

**Comment by lukejpreston** [comment]
@jaiminpanchal27 glad that helped
