### ISSUE TITLE
How to change the title for the generated html report?

### ISSUE THREAD

**Issue by JennyLi90** [lukejpreston/junit_viewer#35]
Are there commands that can change the generated html report's title?
junit-viewer --results=location_for_junit_xml --save=saved_html

**Comment by lukejpreston** [comment]
the output takes the title of the file name minus the extension I think

https://github.com/lukejpreston/junit_viewer/blob/22ed4fe554ace4af72bf0e0a2afa8a3a42c2a559/src/parse.js#L22
