### ISSUE TITLE
Set minify to false by default

### ISSUE THREAD

**Issue by schmunk42** [lukejpreston/junit_viewer#36]
I just ran the viewer of a large number of entries ~10.000 and while it does not finish at all on my MBP with the default setting - it runs in <3 seconds with minify `false`.

related https://github.com/lukejpreston/junit_viewer/issues/31#issuecomment-272584839

**Comment by lukejpreston** [comment]
this project is now deprecated, please see https://github.com/lukejpreston/xunit-viewer which supports the same features
