### ISSUE TITLE
Printing is truncated

### ISSUE THREAD

**Issue by fangly** [lukejpreston/junit_viewer#39]
Hi,

I have just discovered junit-viewer and from what I can see in the [demo](http://lukejpreston.github.io/junit_viewer/demo.html), the functionalities are great. One thing I am missing is the ability to print the report (e.g. to PDF). Specifically, the problem is the presence of the inner scroll bar (on the right) in the "suites_container" element, which causes the print to be truncated when there are many tests.

Changing the height of this element from 516px to 100% fixes this behavior and I suggest it should be the default.

Cheers,

Florent

**Comment by lukejpreston** [comment]
I am in the middle of changing it to this [xunit-viewer](https://lukejpreston.github.io/xunit-viewer) it isn't ready to be used but I think the new view should work. This project will call that one instead.

**Comment by fangly** [comment]
Well done, Luke! It looks like it would print just fine,
