### ISSUE TITLE
Preserve spaces and line breaks in error

### ISSUE THREAD

**Issue by paulo-raca** [lukejpreston/junit_viewer#41]
Thanks for this tools, it is very nice!

One thing that is annoying me is that the stack trace is treated as one big string without line breaks.

Looking at the source code, line breaks and indentation are correctly preserved, so I think you need to use something like a `<pre>` tag to show it?

**Comment by lukejpreston** [comment]
Please upgrade to xunit viewer, this module has been deprecated for a long time and this issue has been addressed there. Let me know if you need help upgrading but it should be pretty straight forward if you follow the docs from there.

**Comment by paulo-raca** [comment]
Thanks!
