### ISSUE TITLE
Manage large numbers of tests

### ISSUE THREAD

**Issue by lukejpreston** [lukejpreston/junit_viewer#6]
If you have a large number of tests it takes a long time to render (I have checked with 2000+ and it starts going really slow)

So I think some pagination should resolve this
It should have have a see X per page dropdown

**Comment by cubicrace** [comment]
I agree ... I have seen slow down with tests of about 1500 also ...

**Comment by lukejpreston** [comment]
This should be improved in version 4 as there will be no server side rendering, no jquery and no animation (it looks a million times nicer)

Hence I am going to close this ticket once version 4 is released

**Comment by lukejpreston** [comment]
Done
